# Generated by Django 3.0.2 on 2020-01-21 05:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost_Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='question_text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 21, 5, 7, 38, 691174, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='post',
            name='downVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='isBoast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upVotes',
            field=models.IntegerField(default=0),
        ),
    ]
